### ISSUE TITLE
Support Apalache type-checking for specs with mutual recursion

### ISSUE THREAD

**Issue by Kukovec** [freespek/ssf-mc#14]
Unlike primitive recursion which, while not supported at the model-checking level, remains type-checkable, mutual recursion results in an error in the typechecking pass. (see https://github.com/freespek/ssf-mc/pull/13#discussion_r1686890811)

We should introduce type-checking support for these operators as well.

**Comment by konnov** [comment]
See https://github.com/apalache-mc/apalache/issues/2978
