### ISSUE TITLE
The structure of the block tree

### ISSUE THREAD

**Issue by banhday** [freespek/ssf-mc#27]
I think we can use the following constraints to describe the structure of the block tree and they may be helpful to reduce the state space. Those contraints are formalized in first-order logic. 

Currently, we have three versions. Version 3 is the best one, and Versions 1 and 2 are old and kept only for reference.
- Version 3: Constraints 14 - 18 on block hashes are added to reduce the symmetry of the block tree.
- Version 2: More constraints on block slots are added to reduce the symmetry of the block tree. The order of constraints is also changed.
- Version 1: The first draft

## Version 3

1. Block $B_{genesis}$ is for slot 0. 
    $0 = B_{genesis}.slot$

2. The block slot is from 0 to $MAX\textunderscore{}SLOT$. 
    $\forall B \colon 0 \leq B.slot \leq MAX\textunderscore{}SLOT$ 
where $MAX\textunderscore{}SLOT$ is a bound of the number of slots.
    
3. Every block has a parent, except a genesis block. 
$\forall B \colon B \neq B_{genesis} \Rightarrow B.parent\textunderscore{}hash \neq \textquotedblleft{}\textquotedblright{}$

4. There exists a block in every slot. 
    $\forall t \colon 0 \leq t \leq MAX\textunderscore{}SLOT \Rightarrow \exists B \colon t = B.slot$ 
    
5. There exist at most two blocks per slot. 
    $\forall t, B_1, B_2, B_3 \colon t = B_1.slot = B_2.slot = B_3.slot \land 0 \leq t \leq MAX\textunderscore{}SLOT \Rightarrow (B_1 = B_3 \lor B_2 = B_3)$

    Another way to formalize this constraint is to use set cardinality $\forall t \colon \vert$ \{ $B \colon B.slot = t$ \} $\vert \leq 2$.
    
6. The parent’s slot is less than its children’s slot. (I think Point 3 may be already captured in predicate IsValidBlock).

7. Blocks whose slosts are $MAX\textunderscore{}SLOT$ have no children. 
    $\forall B \colon B.slot = MAX\textunderscore{}SLOT \Rightarrow \forall B' \colon \lnot is\textunderscore{}parent(B, B')$

8. If a block has a child, this block has a least two children. 
    $\forall B \colon (\exists B_1 \colon is\textunderscore{}parent(B, B_1)) \Rightarrow (\exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2) \land B_1 \neq B_2)$

9. If a block has a child, this block cannot have more than two children. 
    $\forall B, B_1, B_2, B_3 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2)  \land is\textunderscore{}parent(B, B_3) \Rightarrow (B_1 = B_3 \lor B_2 = B_3)$

10. A block can have either no children or exactly two children. This constraint should be implied by the two previous point. 
    (Another way to formalize this constraint is to use set cardinality  $\forall B \colon \vert$ \{ $B' \colon is\textunderscore{}parent(B, B')$ \} $\vert \in$ \{0, 2\}.
      While the encoding with set cardinality does not need Constraints 8 and 9, we are not sure whether this encoding is more helpful for SMT solvers.)
    
11. If block $B$ for slot $t$ has two children, then one child is for slot $t + 1$, and another is for some slot between $t+1$ and $MAX\textunderscore{}SLOT$. 
    $\forall B \colon  \exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2)$
    $\Rightarrow ((B_1.slot = B.slot + 1 \lor B_2.slot = B.slot + 1) \land B.slot + 1 \leq B_1.slot \leq MAX\textunderscore{}SLOT  \land B.slot + 1 \leq B_2.slot \leq MAX\textunderscore{}SLOT)$

12. If block $B$ for slot $t$ has two children, then only one of its children can have children. 
   $\forall B \colon \exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2)$
   $\Rightarrow \lnot ((\exists B_3 \colon is\textunderscore{}parent(B_1, B_3)) \land (\exists B_4 \colon is\textunderscore{}parent(B_2, B_4)))$

13. If block $B'$ has a child and a parent $B$, then $B'$ is for the next slot of $B$. 
    $\forall B' \colon \exists B, B_1 \colon is\textunderscore{}parent(B, B') \land is\textunderscore{}parent(B, B_1) \Rightarrow B'.slot = B.slot + 1$

14. The hash of $B_{genesis}$ is 0. This constraint assumes that we can consider block hashes as natural numbers. We may need to change the type of block hashes from Str to Nat. 
    $0 = has\textunderscore{}block\textunderscore{}hash(B_{genesis})$

15. Every block has a unique hash.
$\forall B, B' \colon has\textunderscore{}block\textunderscore{}hash(B) = has\textunderscore{}block\textunderscore{}hash(B') \Rightarrow B = B'$

16. If block $B$ with a child, then its child has hash $k + 1$ or $k + 2$. 
    $\forall B, B_1 \colon is\textunderscore{}parent(B, B_1) \land has\textunderscore{}block\textunderscore{}hash(B) = k \Rightarrow (has\textunderscore{}block\textunderscore{}hash(B_1) = k + 1 \lor has\textunderscore{}block\textunderscore{}hash(B_1) = k + 2)$

17. If block $B$ with hash $k$ has two children, then one child has hash $k + 1$ and another has hash $k + 2$. 
    This constraint is imply by Constraints 15 and 16.

18. If $B$'s hash is its parent hash + 1 , then $B$ has no children. 
$\forall B \colon has\textunderscore{}block\textunderscore{}hash(B) =  B.parent\textunderscore{}hash + 1 \Rightarrow (\forall B' \colon \lnot is\textunderscore{}parent(B, B'))$

## Version 2
The following constraints are for an old version, and we keep it only for reference.

1. Block $B_{genesis}$ is for slot 0. 
    $0 = B_{genesis}.slot$

2. The block slot is from 0 to $MAX\textunderscore{}SLOT$. 
    $\forall B \colon 0 \leq B.slot \leq MAX\textunderscore{}SLOT$ 
where $MAX\textunderscore{}SLOT$ is a bound of the number of slots.
    
3. Every block has a parent, except a genesis block. 
$\forall B \colon B \neq B_{genesis} \Rightarrow B.parent\textunderscore{}hash \neq \textquotedblleft{}\textquotedblright{}$

4. There exists a block in every slot. 
    $\forall t \colon 0 \leq t \leq MAX\textunderscore{}SLOT \Rightarrow \exists B \colon t = B.slot$ 
    
5. There exist at most two blocks per slot. 
    $\forall t, B_1, B_2, B_3 \colon t = B_1.slot = B_2.slot = B_3.slot \land 0 \leq t \leq MAX\textunderscore{}SLOT \Rightarrow (B_1 = B_3 \lor B_2 = B_3)$

    Another way to formalize this constraint is to use set cardinality $\forall t \colon \vert$ \{ $B \colon B.slot = t$ \} $\vert \leq 2$.
    
6. The parent’s slot is less than its children’s slot. (I think Point 3 may be already captured in predicate IsValidBlock).

7. Blocks whose slosts are $MAX\textunderscore{}SLOT$ have no children. 
    $\forall B \colon B.slot = MAX\textunderscore{}SLOT \Rightarrow \forall B' \colon \lnot is\textunderscore{}parent(B, B')$

8. If a block has a child, this block has a least two children. 
    $\forall B \colon (\exists B_1 \colon is\textunderscore{}parent(B, B_1)) \Rightarrow (\exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2) \land B_1 \neq B_2)$

9. If a block has a child, this block cannot have more than two children. 
    $\forall B, B_1, B_2, B_3 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2)  \land is\textunderscore{}parent(B, B_3) \Rightarrow (B_1 = B_3 \lor B_2 = B_3)$

10. A block can have either no children or exactly two children. This constraint should be implied by the two previous point. 
    (Another way to formalize this constraint is to use set cardinality  $\forall B \colon \vert$ \{ $B' \colon is\textunderscore{}parent(B, B')$ \} $\vert \in$ \{0, 2\}.
      While the encoding with set cardinality does not need Constraints 8 and 9, we are not sure whether this encoding is more helpful for SMT solvers.)
    
11. If block $B$ for slot $t$ has two children, then one child is for slot $t + 1$, and another is for some slot between $t+1$ and $MAX\textunderscore{}SLOT$. 
    $\forall B \colon  \exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2)$
    $\Rightarrow ((B_1.slot = B.slot + 1 \lor B_2.slot = B.slot + 1) \land B.slot + 1 \leq B_1.slot \leq MAX\textunderscore{}SLOT  \land B.slot + 1 \leq B_2.slot \leq MAX\textunderscore{}SLOT)$

12. If block $B$ for slot $t$ has two children, then only one of its children can have children. 
   $\forall B \colon \exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2)$
   $\Rightarrow \lnot ((\exists B_3 \colon is\textunderscore{}parent(B_1, B_3)) \land (\exists B_4 \colon is\textunderscore{}parent(B_2, B_4)))$

13. If block $B'$ has a child and a parent $B$, then $B'$ is for the next slot of $B$. 
    $\forall B' \colon \exists B, B_1 \colon is\textunderscore{}parent(B, B') \land is\textunderscore{}parent(B, B_1) \Rightarrow B'.slot = B.slot + 1$

Constraints 7, 12 and 13 imply the two following constraints:

a. If block $B'$ is the only child of $B$ such that $B'.slot = B.slot + 1$ and $B'.slot < MAX\textunderscore{}SLOT$, then $B'$ has children.

b. If two children of block $B$ are for the same slot $B.slot + 1 < MAX\textunderscore{}SLOT$, then only child of $B$ has children.

## Version 1
The following constraints are for an old version, and we keep it only for reference.

1. Every block has a parent, except a genesis block.
$\forall B \colon B \neq B_{genesis} \Rightarrow B.parent\textunderscore{}hash \neq \textquotedblleft\textquotedblright$
2. Evey block has exactly two children, except leaf nodes. This constraint is formalized with the two following formulas:
$\forall B \colon (\exists B_1 \colon is\textunderscore{}parent(B, B_1)) \Rightarrow (\exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2) \land B_1 \neq B_2)$
$\forall B, B_1, B_2, B_3 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2)  \land is\textunderscore{}parent(B, B_3) \Rightarrow (B_1 = B_3 \lor B_2 = B_3)$
where predicate $is\textunderscore{}parent(B, B')$ is to check whether block $B$ is the parent of block $B'$, i.e., $B = get\textunderscore{}block\textunderscore{}from\textunderscore{}hash(B'.parent\textunderscore{}hash, node\textunderscore{}tate)$. The first formula is to ensure that a block cannot have only one child, and the second is to ensure that a block cannot have more than two children.
3. The parent’s slot is less than its children’s slot. (I think Point 3 may be already captured in predicate IsValidBlock).
4. There exists a block in every slot. 
$\forall t \colon t < MAX\textunderscore{}SLOT \Rightarrow \exists B \colon t = B.slot$
where $MAX\textunderscore{}SLOT$ is a bound of the number of slots.
5. There exist at most two blocks per slot. 
$\forall B_1, B_2, B_3 \colon B_1.slot = B_2.slot = B_3.slot = t \land 0 < t <= MAX\textunderscore{}SLOT \Rightarrow (B_1 = B_3 \lor B_2 = B_3)$
6. Only block $B_{genesis}$ is for slot 0.
$\forall B \colon B.slot = 0 \Rightarrow B = B_{genesis}$
7. Assume that block $B$ for slot $t$ has two children $B_1$ and $B_2$, then $B_1$ is for slot $t + 1$, and $B_2$ is for some slot between $t+1$ and $t+D$ where $D$ is a user-given constant.
$\forall B \colon \exists B_1, B_2 \colon is\textunderscore{}parent(B, B_1) \land is\textunderscore{}parent(B, B_2) \Rightarrow (B_1.slot = B.slot + 1 \land B.slot + 1 \leq B_2.slot \leq B.slot + D)$
8. Assume that block $B$ is a parent of block $B'$ and $B'.slot = B.slot + 1$. Then, $B'$ has no child.
$\forall B, B' \colon is\textunderscore{}parent(B, B') \land  B'.slot = B.slot + 1 \Rightarrow \forall B_1 \colon \lnot  is\textunderscore{}parent(B', B_1)$

**Comment by saltiniroberto** [comment]
In the Version 3 above, by $\mathit{has\\_block\\_hash}(B)$ @banhday  means the block hash of $B$.

**Comment by konnov** [comment]
In the end, we have introduced different network configurations in Spec 4b. So I think we have followed this suggestion, but in a slightly different manner.
