### ISSUE TITLE
Constraints on VOTE messages 

### ISSUE THREAD

**Issue by banhday** [freespek/ssf-mc#28]
I think we can put the following constraints on VOTE messages to the validity predicate for initial states.

1. For every message $\left[ VOTE, B, S \rightarrow T, t, v \right]$, we have
    a. $1 \leq t \leq MAX\textunderscore{}SLOT$ 
    b. Let **B** be the set of all blocks. Then, block $B$ is member of **B**.
    c. The source checkpoint is a member of **B**.
    d. Block $B$ is the target checkpoint. 
        (This constraint is not really correct in Algorithms 3 and 5. 
        However, as the proof of validity safety does not consider a head vote, it is safe to have this constraint. 
        Another option is to set the target checkpoint to the genesis block but this option is less correct. )
    e. $S \rightarrow T$ is a valid FFG vote.
    f. The slot of the target checkpoint is $t$.

    We can formalize this constraint in the following way
    $\forall \left[ VOTE, B, S \rightarrow T, t, v_i \right] \colon$
    $\qquad \land 1 \leq t \leq MAX\textunderscore{}SLOT$
    $\qquad \land B \in \textbf{B}$
    $\qquad \land get\textunderscore{}block\textunderscore{}from\textunderscore{}hash(S.block\textunderscore{}hash) \in \textbf{B}$
    $\qquad \land B = get\textunderscore{}block\textunderscore{}from\textunderscore{}hash(T.block\textunderscore{}hash)$
    $\qquad \land is\textunderscore{}valid(S \rightarrow T)$
    $\qquad \land T.chkp\textunderscore{}slot = t$

2. Every honest validator $v_i$ has exactly one VOTE message for every slot $1 \leq t \leq MAX\textunderscore{}SLOT$.
    $\forall v, m_1, m_2 \colon is\textunderscore{}honest(v) \land m_1.v = m_2.v = v \land m_1.t = m_2.t \land 1 \leq t \leq MAX\textunderscore{}SLOT \Rightarrow m_1 = m_2$

3. A Byzantine validator has at most two votes in every slot $1 \leq t \leq MAX\textunderscore{}SLOT$.
    $\forall v, m_1, m_2, m_3 \colon is\textunderscore{}Byz(v) \land m_1.v = m_2.v = m_3.v = v \land m_1.T.chkp\textunderscore{}slot= m_2.T.chkp\textunderscore{}slot = m_3.T.chkp\textunderscore{}slot  \land 1 \leq m_1.T.chkp\textunderscore{}slot  \leq MAX\textunderscore{}SLOT \Rightarrow m_1 = m_3 \lor m_2 = m_3$

    Another way to encode this constraint is 
    $\forall v, t \colon is\textunderscore{}Byz(v) \land 1 \leq t \leq MAX\textunderscore{}SLOT \Rightarrow \vert \{ m \colon m.T.chkp\textunderscore{}slot  = t \land m.v = v \land is\textunderscore{}valid(m) \} \vert \leq 2$

**Comment by thpani** [comment]
One question for (1.a) + (1.f): if we take the block tree from #27, we will have blocks in slots up to `MAX_SLOT` (inclusive).

AFAIU, to finalize the tip of the chain (proposed at `MAX_SLOT`), we'd have to consider votes with checkpoints up to `MAX_SLOT+2` (`MAX_SLOT+1` for the justifying vote, and `MAX_SLOT+2` for the finalizing vote).

Should 1.a be $1 \leq t \leq MAX\textunderscore{}SLOT + 2$, or is there some other justification for cutting off the span of votes earlier?

**Comment by konnov** [comment]
The constraints in (1) make sense to me. Also, (2) is ok, though currently we just assume that all validators are behaving in arbitrary way, kind of Byzantine. I can see how (3) could be useful, but is not it restricting the solution space a lot?

It would probably help us, if we could see how (2)-(3) contributed to accountable safety.

**Comment by konnov** [comment]
Shall we close this one, since we are finalizing the report?
