### ISSUE TITLE
Things to check about the Python spec

### ISSUE THREAD

**Issue by thpani** [freespek/ssf-mc#7]
- [x] Should [`ProposeMessage.proposer_view`](https://github.com/saltiniroberto/ssf/blob/7ea6e18093d9da3154b4e396dd435549f687e6b9/high_level/common/data_structures.py#L62) be a vector or a set?
- [x] `validator_set_weight` drops weights occurring multiple times: https://github.com/freespek/ssf-mc/pull/10#discussion_r1681022933

**Comment by konnov** [comment]
> * [x]  Should [`ProposeMessage.proposer_view`](https://github.com/saltiniroberto/ssf/blob/7ea6e18093d9da3154b4e396dd435549f687e6b9/high_level/common/data_structures.py#L62) be a vector or a set?

In the long run, it is supposed to be a vector

**Comment by thpani** [comment]
We still have references to this issue in the spec, please keep it open until they're all removed :)
